# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action

name: Translate Environment
description: 'Translate vars based on environment'
inputs:
  environment:
    description: 'Environment name'
    default: development
    required: true
outputs:
  short-name:
    description: 'Short name of environment'
    value: ${{ steps.translate.outputs.short-name }}

runs:
  using: composite
  steps:
    - id: translate
      env:
        ENVIRONMENT: ${{ inputs.environment }}
      shell: bash
      run: |
        if [ "${ENVIRONMENT}" == "production" ]; then
          echo "short-name=prod" >> $GITHUB_OUTPUT
        elif [ "${ENVIRONMENT}" == "development" ]; then
          echo "short-name=dev" >> $GITHUB_OUTPUT
        else
          echo "Unsupported environment: ${ENVIRONMENT}" >&2
          exit 1
        fi
