# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action

name: API Environment Settings
description: 'Get build vars based on environment'
inputs:
  environment:
    description: 'Environment name'
    required: true
outputs:
  short-name:
    description: 'Short name of environment'
    value: ${{ steps.env-vars.outputs.short-name }}
  ecr-repository-name:
    description: 'Name of the ECR repository for environment'
    value: ${{ steps.env-vars.outputs.ecr-repository-name }}
  ecs-cluster-name:
    description: 'Name of the ECS cluster for environment'
    value: ${{ steps.env-vars.outputs.ecs-cluster-name }}
  ecs-service-name:
    description: 'Name of the ECS service for environment'
    value: ${{ steps.env-vars.outputs.ecs-service-name }}
  ecs-task-definition-template:
    description: 'The location of the ECS task definition json for the environment'
    value: ${{ steps.env-vars.outputs.ecs-task-definition-template }}
  ecs-task-container-name:
    description: 'Name of the container in the task definition for the API image'
    value: ${{ steps.env-vars.outputs.ecs-task-container-name }}


runs:
  using: composite
  steps:
    - id: env-vars
      env:
        ENVIRONMENT: ${{ inputs.environment }}
      shell: bash
      run: |
        if [ "${ENVIRONMENT}" == "production" ]; then
          SHORT_NAME=prod
        elif [ "${ENVIRONMENT}" == "development" ]; then
          SHORT_NAME=dev
        else
          echo "Unsupported environment: ${ENVIRONMENT}" >&2
          exit 1
        fi
        APP_PREFIX=reachwell-api
        # Convention used in AWS resources
        AWS_PREFIX=${APP_PREFIX}-${SHORT_NAME}
        # Output
        echo >> $GITHUB_OUTPUT <<EOF
        short-name=${SHORT_NAME}
        ecr-repository-name=${AWS_PREFIX}-repository
        ecs-cluster-name=${AWS_PREFIX}-cluster
        ecs-service-name=${AWS_PREFIX}-service
        ecs-task-definition-template=.github/aws/${AWS_PREFIX}-task.json
        ecs-task-container-name=${AWS_PREFIX}
        EOF
