name: Dispatch Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - staging
          - production
        required: true
        default: 'staging'
      version:
        description: 'Version (image tag)'
        required: true
        type: string
        default: 'latest'
      deploy_image:
        description: 'Deploy image'
        type: boolean
        required: true
        default: true
      deploy_ecs:
        description: 'Deploy ECS'
        type: boolean
        required: true
        default: true


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Dispatch Test"
          echo "${{ inputs }}"
      - name: Echo DEVELOP
        run: |
          echo "Hello from the DEVELOP branch"