# ./.github/workflows/publish.yml
# https://nx.dev/recipes/nx-release/publish-in-ci-cd
name: Publish

on:
  # push:
  #   tags:
  #     - v*.*.*
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        default: true

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: jflygare/cicd-sandbox           # set this to your Amazon ECR repository name
  

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write # to be able to publish packages
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'

      - name: NPM auth
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm clean-install
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Build package
        #run: npx nx run cicd-sandbox:build
        run: npx nx run-many -t build
        shell: bash

      - name: Version package
        run: npx nx release version
        shell: bash

      - name: Read version
        id: version
        run: echo "version=$(node -p "require('./dist/apps/cicd-sandbox/package.json').version")" >> $GITHUB_OUTPUT

      - name: Echo version
        run: echo ${{ steps.version.outputs.version }}

      - name: Publish package
        if: false
        run: npx nx release publish --dry-run=${{ inputs.dryRun }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.version.outputs.version }}
          #IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -f apps/cicd-sandbox/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT