name: TEST

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Git Environment'
        type: environment
        required: true
      raw-environment:
        description: 'Environment'
        type: choice
        options:
          - development
          - staging
          - production
        required: true
        default: 'staging'

jobs:
  env-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Eco Env
        run: echo "${{ inputs.environment }}"

      - run: echo "${SEC_VAL}"
        env:
          SEC_VAL: ${{ secrets.ENV_SECRET }}

      - run: echo "${SEC_VAL}"
        env:
          SEC_VAL: ${{ toJSON(secrets) }}

  test-reuse:
    uses: ./.github/workflows/reuseme.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # This prints the entire github model values for troubleshooting/testing. This can be removed if no longer useful
      - name: Echo github
        run: echo "${{ toJSON(github) }}"

      - uses: ./.github/actions/env-api
        id: get-env
        with:
          environment: ${{ inputs.environment }}

      - run: echo "${{ toJSON(steps.get-env.outputs )}}"

      - run: env | sort

      - run: |
          echo "This is a summary" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo "${JSON}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        env:
          JSON: ${{ toJSON(steps.get-env.outputs )}}


