name: TEST

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - development
          - staging
          - production
        required: true
        default: 'staging'

jobs:
  test-reuse:
    uses: ./.github/workflows/reuseme.yml
    with:
      environment: ${{ inputs.environment }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # This prints the entire github model values for troubleshooting/testing. This can be removed if no longer useful
      - name: Echo github
        run: echo "${{ toJSON(github) }}"

      - uses: ./.github/actions/env-api
        id: get-env
        with:
          environment: ${{ inputs.environment }}

      - run: echo "${{ toJSON(steps.get-env.outputs )}}"


